inputFormat: xml
context: testContext

databasesUnderTest:
  - name: yugabytedb
    version: ${YUGABYTE_RELEASE_NUMBER}
    url: jdbc:postgresql://localhost:5433/lbcat
    username: yugabyte
    password: yugabyte